In [174]:
import requests
import pandas as pd
import json

#### Задача 1####
- Найти все произведения, связанные с ананасами. 
- Выбрать id тех объектов, которые присутствуют в списке (40007, 156931, 450114, 418070, 436524).

In [175]:
#выполним поиск по слову 'pineapples'
r = requests.get('https://collectionapi.metmuseum.org/public/collection/v1/search?q=pineapples')
res = r.json()

In [176]:
#Сохраним id полученных объектов в список pineapples_ids
pineapples_ids = res['objectIDs']
pineapples_ids

[116529,
 911514,
 272802,
 122490,
 210092,
 212297,
 212315,
 219424,
 226020,
 221345,
 215263,
 212290,
 221473,
 221683,
 446149,
 221469,
 227414,
 226325,
 226242,
 221682,
 221685,
 226237,
 226238,
 226236,
 221684,
 221519,
 226235,
 227614,
 221681,
 272485,
 272486,
 765285,
 192910,
 830252,
 830253,
 283087,
 11837,
 272735,
 272730,
 272734,
 272736,
 272731,
 272732,
 187161,
 202512,
 11938,
 19080,
 13868,
 272739,
 272738,
 272737,
 259968,
 155983,
 155772,
 155982,
 16910,
 156779,
 156931,
 158133,
 13857,
 13888,
 435414,
 407839,
 195290,
 158244,
 641083,
 228211,
 11939,
 660590,
 660593,
 461382,
 76091,
 450114,
 402616,
 158138,
 158140,
 210179,
 660348,
 358992,
 13876,
 312277,
 448412,
 843688,
 223005,
 888156,
 229289,
 746852,
 889447,
 316796,
 725719]

In [177]:
bucket = list()
l = [40007, 156931, 450114, 418070, 436524]
for i in l:
    if i in pineapples_ids:
            bucket.append(i)
    else:
        continue
print(bucket)

[156931, 450114]


**Ответ**: при поиске по объектам, связаным с ананасами, были найдены два объекта из списка: 156931, 450114.

#### Задача 2#### 
- Cобрать информацию об объекте 156931:
  - department – департамент
  - culture – культура
  - artist_name – автор
  - title – название
  - object_name – название/категория объекта
  - object_id – id объекта
  - object_URL - URL-адрес

In [178]:
r = requests.get('https://collectionapi.metmuseum.org/public/collection/v1/objects/156931')
result = r.json()
result

{'objectID': 156931,
 'isHighlight': False,
 'accessionNumber': '2009.300.2139a–c',
 'accessionYear': '2009',
 'isPublicDomain': True,
 'primaryImage': 'https://images.metmuseum.org/CRDImages/ci/original/68.135.12a-c_CP4.jpg',
 'primaryImageSmall': 'https://images.metmuseum.org/CRDImages/ci/web-large/68.135.12a-c_CP4.jpg',
 'additionalImages': [],
 'constituents': None,
 'department': 'Costume Institute',
 'objectName': 'Accessory Set',
 'title': 'Accessory set',
 'culture': 'Philippine',
 'period': '',
 'dynasty': '',
 'reign': '',
 'portfolio': '',
 'artistRole': '',
 'artistPrefix': '',
 'artistDisplayName': '',
 'artistDisplayBio': '',
 'artistSuffix': '',
 'artistAlphaSort': '',
 'artistNationality': '',
 'artistBeginDate': '',
 'artistEndDate': '',
 'artistGender': '',
 'artistWikidata_URL': '',
 'artistULAN_URL': '',
 'objectDate': 'ca. 1850',
 'objectBeginDate': 1848,
 'objectEndDate': 1852,
 'medium': 'piña',
 'dimensions': '',
 'measurements': [{'elementName': 'Overall',
   '

In [179]:
data_object = {'department': [result["department"]], 
'culture': [result["culture"]], 
'artist_name': [result["artistDisplayName"]], 
'title': [result["title"]], 
'object': [result["objectName"]], 
'object_id': [result["objectID"]],
'object_URL':[result["objectURL"]]}
final_result = pd.DataFrame(data_object)
final_result

department     culture artist_name          title         object  \
0  Costume Institute  Philippine              Accessory set  Accessory Set   

   object_id                                         object_URL  
0     156931  https://www.metmuseum.org/art/collection/searc...

**Ответ**:
   - Департамент: *Институт костюма*
   - Культура: *Филиппины*
   - Автор:
   - Название: *Набор аксессуаров*
   - Категория объекта: *Набор аксессуаров*
   - Id объекта: *156931*
   - URL объекта: *https://www.metmuseum.org/art/collection/search/156931*

#### Задача 3 ####
- Написать цикл, с помощью которого будет собрана информация об объектах, которые были получены в задаче 1. 
- Результаты записать в датафрейм:

 - object_id – id объекта
 - accession_year - год поступления в коллекцию музея
 - title – название
 - artist_name – автор
 - department – департамент
 - object_begin_date – дата (начало)
 - object_end_date – дата (конец)
 - period – название периода
 - object_name – название/категория объекта
 - culture – культура
- К каким культурам относятся объекты? Подсчитать количество объектов, у которых в данном разделе ничего не указано.

In [180]:
# распарсим json через словарь
setdata = pd.DataFrame()
for i in pineapples_ids:
    try:
        r = requests.get('https://collectionapi.metmuseum.org/public/collection/v1/objects/' + str(i))
        result = r.json()
        data = {'object_id': [result['objectID']],
                'accession_year': [result['accessionYear']],
                'title': [result['title']], 
                'artist_name': [result['artistDisplayName']], 
                'department': [result['department']], 
                'object_begin_date': [result['objectBeginDate']], 
                'object_end_date': [result['objectEndDate']], 
                'period': [result['period']], 
                'object_name': [result['objectName']], 
                'culture': [result['culture']]}
        df = pd.DataFrame(data)
        setdata = pd.concat([setdata, df], ignore_index=True)
    except:
        continue
setdata

object_id accession_year  \
0      116529           1941   
1      911514           1994   
2      272802           1994   
3      122490           1951   
4      210092           1908   
..        ...            ...   
84     229289           1970   
85     746852           1944   
86     889447           1954   
87     316796           1993   
88     725719           1973   

                                                title   artist_name  \
0                                           Sunbonnet                 
1                         Growing Pineapples, Florida                 
2   [Woman Preparing Pineapples in Kitchen Courtya...  Walker Evans   
3                                        Handkerchief                 
4                                            Fan leaf                 
..                                                ...           ...   
84                                           Bedcover                 
85  Ornamental designs with thin bundles of styliz...   Jules Dumas   
86                       The New York Cries, in Rhyme    Mahlon Day   
87      Receptacle with Figurative Relief and Stopper                 
88  Choix, "Planche III: Appareils d’Éclairage: Su...    Paul Iribe   

                                department  object_begin_date  \
0                        Costume Institute               1865   
1                              Photographs               1910   
2                              Photographs               1933   
3                        Costume Institute               1800   
4   European Sculpture and Decorative Arts               1800   
..                                     ...                ...   
84  European Sculpture and Decorative Arts               1725   
85                     Drawings and Prints               1844   
86                     Drawings and Prints               1834   
87         The Michael C. Rockefeller Wing               1880   
88                     Drawings and Prints               1930   

    object_end_date period                           object_name  \
0              1875                                    Sunbonnet   
1              1939                                     Postcard   
2              1933                                     Negative   
3              1899                                 Handkerchief   
4              1899                                     Fan leaf   
..              ...    ...                                   ...   
84             1750                                     Bedcover   
85             1900           Book Print Ornament & Architecture   
86             1834                                         Book   
87             1890                          Vessel with stopper   
88             1930         Book Print Ornament and Architecture   

                      culture  
0                      Indian  
1                              
2                              
3                     Spanish  
4                              
..                        ...  
84                             
85                             
86                             
87  Kongo peoples; Vili group  
88                             

[89 rows x 10 columns]

In [167]:
setdata['culture'].unique()

array(['Indian', '', 'Spanish', 'American', 'French', 'Philippine',
       'Chinese', 'Italian',
       'India (Coromandel Coast), for Indonesian market',
       'Fon peoples, Danhomè Kingdom', 'Kongo peoples; Vili group'],
      dtype=object)

In [181]:
setdata.query("culture == ''")['culture'].count()

64

**Ответ:** Объекты,связанные с ананасами, относятся к культуре Индии, Испании, Америки, Франции, Филиппин, Китая, Италии, Коромандельского побережья Индии (для рынка Индонезии), народа Фон Королевства Дагомея, этнической группы Вили народа Конго. У 64 объектов в разделе "культура" стоит знак пропуска.

#### Задача 5 ####
- Построить запрос через секцию "Search".
- Выполнить поисковый запрос для департамента "Drawings and Prints" (departmentId = 9) с тегом "mountains" и записать первые 100 id объектов в датафрейм (по аналогии с датафреймом в задаче 4).
- Найти художника, которому принадлежит большинство работ, находящихся на хранении в музее.
- Найти год, в который поступило болшинство объектов в коллекцию музея.

In [182]:
r = requests.get('https://collectionapi.metmuseum.org/public/collection/v1/search?departmentId=9&q=mountains')
mountains = r.json()

In [183]:
mountains_id = mountains['objectIDs']

In [184]:
setdata_mountains = pd.DataFrame()
for i in mountains_id[:100]:
    try:
        r = requests.get('https://collectionapi.metmuseum.org/public/collection/v1/objects/' + str(i))
        result = r.json()
        data = {'object_id': [result['objectID']],
                'accession_year': [result['accessionYear']],
                'title': [result['title']], 
                'artist_name': [result['artistDisplayName']], 
                'department': [result['department']], 
                'object_begin_date': [result['objectBeginDate']], 
                'object_end_date': [result['objectEndDate']], 
                'period': [result['period']], 
                'object_name': [result['objectName']], 
                'culture': [result['culture']]}
        df = pd.DataFrame(data)
        setdata_mountains = pd.concat([setdata_mountains, df], ignore_index=True)
    except:
        continue
setdata_mountains

object_id accession_year  \
0      909824           1987   
1      393610           2010   
2      709307           1992   
3      418070           1946   
4      351248           2001   
..        ...            ...   
95     371827           2006   
96     688154           1959   
97     355427           1917   
98     383910           2008   
99     381626           2008   

                                                title  \
0                                           Mountains   
1                Mountain Phacelia (Phacelia Sericea)   
2   Untitled, broadside cover for the poem "The So...   
3            Mountain Drives of Mohonk Lake, New York   
4                            Landscape with Mountains   
..                                                ...   
95  Mountainous Landscape with Ruins of a Castle a...   
96                         View of a Mountain Village   
97  Kitchen Staff (recto); Mountainous Landscape w...   
98  Reclining Man in a Mountainous Landscape with ...   
99                        Mountainous River Landscape   

                                          artist_name           department  \
0                                      Robert Kipniss  Drawings and Prints   
1                          Margaret Neilson Armstrong  Drawings and Prints   
2                                          Cy Twombly  Drawings and Prints   
3   Lake Mohonk Mountain House, Mohonk Lake, New York  Drawings and Prints   
4         Antonio d'Enrico Tanzio (Tanzio da Varallo)  Drawings and Prints   
..                                                ...                  ...   
95                                Johann Caspar Huber  Drawings and Prints   
96                                      Eugène Isabey  Drawings and Prints   
97                                         John Leech  Drawings and Prints   
98                            Johann Georg von Dillis  Drawings and Prints   
99                                     Jacob Esselens  Drawings and Prints   

    object_begin_date  object_end_date period object_name culture  
0                1963             1973              Print          
1                1909             1909            Drawing          
2                1952             1952                             
3                1900             1940               Book          
4                1575             1633            Drawing          
..                ...              ...    ...         ...     ...  
95               1752             1827            Drawing          
96               1829             1833              Print          
97               1837             1864            Drawing          
98               1770             1841            Drawing          
99               1635             1687            Drawing          

[100 rows x 10 columns]

In [185]:
setdata_mountains['artist_name'].value_counts()

Joseph Mallord William Turner    7
Stefano della Bella              5
Rodolphe Bresdin                 4
Eugène Delacroix                 4
Samuel Palmer                    3
                                ..
John Rubens Smith                1
Jan van der Meer the Younger     1
Franz Schütz                     1
Johann Caspar Huber              1
                                 1
Name: artist_name, Length: 74, dtype: int64

In [186]:
setdata_mountains['accession_year'].value_counts()

2001    6
2006    6
2012    6
1953    5
1928    5
2016    4
2009    4
1917    4
1962    3
1951    3
1946    3
2005    3
1952    2
1959    2
1923    2
2008    2
1996    2
1999    2
1975    2
1963    2
1956    2
1930    1
1929    1
        1
1967    1
1955    1
1980    1
1971    1
1974    1
1961    1
2015    1
1958    1
1949    1
1992    1
1922    1
1960    1
2011    1
2014    1
2007    1
1954    1
1926    1
2010    1
1880    1
2013    1
1921    1
1957    1
2004    1
2023    1
1987    1
1976    1
1972    1
Name: accession_year, dtype: int64

**Ответ:** Из 100 музейных объектов, относящихся к департаменту "Drawings and Prints" и связанных с горами, большинство работ принадлежит художнику Уильяму Тёрнеру. Самое большое количество объектов из 100 поступило в коллекцию музея в 2001, 2006 и 2012.